version: "3"

services:
  nginx:
    build: ./bin/nginx/
    container_name: wjcrypto-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ${DOCUMENT_ROOT-./www/html}:/var/www/html

  php:
    build: ./bin/php/
    container_name: wjcrypto-php
    expose:
      - 9000
    volumes:
      - ${DOCUMENT_ROOT-./www/html}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
    links:
      - mysql
    environment:
      PHP_IDE_CONFIG: "serverName=wjcrypto"

  mysql:
    image: mysql:5.7
    container_name: wjcrypto-mysql
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
